### ISSUE TITLE
close blogs.perl.org (or repair)

### ISSUE THREAD

**Issue by wollmers** [blogs-perl-org/blogs.perl.org#299] opened 2015-07-07 09:29 UTC
We can see from all the login issues here, that blogs.perl.org has a serious problem. It has it for a long time now. It isn't solved for a long time now. So please shut down the site, or change the blog software.

**Comment by markwellis** [comment] 2015-07-07 10:34
don't close it, but change the software yes. it's a joke, it doesn't work. move to wordpress or something, anything is better than how it is now.

**Comment by karenetheridge** [comment] 2015-07-07 15:19
+1, I haven't been able to log in since last year.

**Comment by awohld** [comment] 2015-07-07 21:36
How about we migrate this domain to WordPress with all the existing content and users and place adds on here then divert the revenue to fuel Perl growth.  This domain and content are valuable and could be used to further the community.

**Comment by karenetheridge** [comment] 2015-07-07 21:45
@awold unless you're volunteering, saying that isn't terribly helpful.  We all have lots of ideas for making things better, but what matters is action.

**Comment by awohld** [comment] 2015-07-07 23:07
I'm not saying I'm volunteering or not, but what's an acceptable solution to the community?  

I can try to replicate this in wordpress and recreate the users and posts if that's acceptable.  

But if the answer is fixing movable type and getting a MT pro to fix it is a better/faster answer, then I might not be the right person.  If finding a MT person is the answer and there isn't a volunteer, how much $$$ will it cost to fix and where can we get the $$$.

And before anyone asks... I'm not saying I'm not willing to volunteer $$$... again it depends on the MT oprion estimate vs WordPress option.

**Comment by djzort** [comment] 2015-07-08 00:24
i have been asking to help out over and over again, even putting together this "work around" (https://github.com/blogs-perl-org/blogs.perl.org/issues/294) and posting it to the front page.

perhaps blogs.perl.org could be hosted by bluehost/gatorhost as a gift to the community, they could also link themselves to make it more worth their while.

**Comment by awohld** [comment] 2015-07-08 01:50
I don't think it's a hosting issue.  From the comments on #294 it seems like knowledge of MT inner workings is an issue.  I don't mind paying for hosting.

Who controls where the subdomains point for Perl.org?  If they agree to point it to a new acceptible replacement blog that's WordPress with all the posts / comments migrated I'll try making a new blog.

**Comment by djzort** [comment] 2015-07-08 02:23
in theory, if using a company who hosts and maintains mt as a product - the upgrade problems should be taken care of along with all the other customers.

**Comment by awohld** [comment] 2015-07-08 03:36
Ok, I see what you're saying.  I emailed the registrant of Perl.org to see if they're open to pointing blogs.perl.org somewhere else.

**Comment by djzort** [comment] 2015-07-08 04:23
some people are 100% fine and others like myself are having massive issues. given that different login urls work/dont work - i cant help but think something has gone wrong with the upgrade. having two login locations seems like a relic has been left over, and mixed login results sounds to me like there are two user tables... a relic of a failed upgrade. thats just my 2c though.

**Comment by djzort** [comment] 2015-07-08 04:25
heres another 2c. i would recommend sticking with something perl rather than using wordpress. it pains me enough that pm.org lists are using mailman rather than sympa :)

**Comment by makot** [comment] 2015-07-19 15:46
FYI, The Perl Foundation got this:
[Grant Proposal: Revitalize blogs.perl.org](http://news.perlfoundation.org/2015/07/grant-proposal-revitalize-blog.html)

**Comment by endosynth** [comment] 2016-01-29 17:33
I've been trying to log in but haven't been able to.

**Comment by ap** [comment] 2020-05-26 11:17
I assumed all responsibility for the site a short while ago.

Multiple failed TPF grants later, it should be clear that well-meaning offers to do something about the site aren’t the solution, *even if backed by action*. The problem is not *migrating* to something better, the problem is keeping it going *after* that. That’s already the problem with b.p.o itself – our MT setup was work donated by SixApart, but SixApart manpower for maintaining it dried up soon after, and we didn’t have the expertise to maintain the setup ourselves. So there has been no one at the wheel for a long time. And every attempt to replace the software has suffered from the same problem: what the site needs is not any particular technical solution, it’s *someone who can maintain it*.

I intend to do that. I’ll be working to get the site off of MT in my off time, but it’s not going to happen quickly.

(And I’m not touching the WordPress suggestion. 🙂)

**Closed by ap** 2020-05-26 11:17 UTC
Labels: meta
