### ISSUE TITLE
your session expired, without preview

### ISSUE THREAD

**Issue by vsespb** [blogs-perl-org/blogs.perl.org#222] opened 2013-08-01 21:08 UTC
I've just was tried to post something, and got "your session is expired". I reloaded page - same result. I was logged in. I logged out and re-login. After that posting was successful.

And I did not use "post preview".

my login on forum: `vsespb`

related: #215

**Comment by awake416** [comment] 2015-02-11 06:51
Same here, I logged in and within a minute, i wrote the content in comment box, then preview and it submit, it says session expired. Same thing when i do after clicking back button worked.

**Comment by ap** [comment] 2024-10-25 01:32
This is a duplicate of #196, [which I fixed a while ago](/blogs-perl-org/blogs.perl.org/issues/196#issuecomment-835631396).

**Closed by ap** 2024-10-25 01:32 UTC
Labels: bug
