### ISSUE TITLE
414 response when clicking link

### ISSUE THREAD

**Issue by 1nickt** [blogs-perl-org/blogs.perl.org#351] opened 2018-12-06 12:54 UTC
Hi,

I went to:
http://blogs.perl.org/mt/mt-search.fcgi?limit=20&search=byterock

I clicked on the link "28" (trying to go to earliest post). (Also happens when clicking "Next".)

The URL in the browser location bar was:
http://blogs.perl.org/mt/mt-search.fcgi?search=byterock&IncludeBlogs=127%2C1801%2C71%2C1648%2C1481%2C2927%2C2266%2C3163%2C1178%2C1387%2C512%2C1932%2C463%2C517%2C458%2C2634%2C1785%2C1250%2C1363%2C722%2C2507%2C1109%2C1630%2C1597%2C3185%2C728%2C1244%2C2154%2C1638%2C742%2C29%2C350%2C1969%2C1810%2C2203%2C58%2C153%2C2932%2C2754%2C2387%2C101%2C2994%2C340%2C3256%2C311%2C825%2C917%2C2425%2C495%2C1703%2C2086%2C1322%2C1816%2C2460%2C2510%2C1172%2C2458%2C1259%2C834%2C285%2C2441%2C1216%2C3238%2C2285%2C2194%2C1135%2C2002%2C1203%2C96%2C1068%2C1667%2C2114%2C486%2C2134%2C1354%2C569%2C8%2C3239%2C2359%2C3111%2C2045%2C1396%2C686%2C3149%2C1760%2C391%2C943%2C2676%2C1887%2C2907%2C1375%2C180%2C1585%2C2939%2C1877%2C246%2C2705%2C2227%2C690%2C3241%2C1168%2C61%2C536%2C1767%2C2237%2C1688%2C2394%2C1266%2C2654%2C2958%2C1458%2C444%2C508%2C1336%2C39%2C3260%2C1089%2C558%2C12%2C3200%2C1554%2C2168%2C573%2C2710%2C1084%2C638%2C875%2C2479%2C1522%2C1%2C3218%2C506%2C116%2C136%2C1197%2C2937%2C2146%2C3157%2C2845%2C2482%2C2719%2C581%2C2727%2C308%2C678%2C1517%2C2808%2C3025%2C3004%2C1975%2C2910%2C1973%2C1991%2C3027%2C927%2C301%2C3180%2C2302%2C51%2C1758%2C1822%2C456%2C2745%2C652%2C1033%2C2736%2C2258%2C2034%2C2029%2C796%2C2349%2C366%2C844%2C1541%2C2723%2C272%2C775%2C3044%2C2108%2C20%2C888%2C3100%2C1754%2C1627%2C1161%2C468%2C2093%2C3030%2C1019%2C700%2C1927%2C78%2C2853%2C990%2C413%2C294%2C1614%2C1442%2C764%2C349%2C1743%2C2075%2C3251%2C3205%2C2081%2C1383%2C606%2C137%2C1414%2C2522%2C1855%2C666%2C432%2C1074%2C860%2C2308%2C1567%2C1063%2C1776%2C2565%2C3047%2C2576%2C2362%2C708%2C2583%2C2796%2C2589%2C2814%2C710%2C1656%2C323%2C856%2C2142%2C1834%2C1664%2C112%2C3211%2C545%2C191%2C2733%2C2467%2C187%2C588%2C1684%2C756%2C2326%2C1283%2C262%2C1944%2C3089%2C212%2C2436%2C1331%2C2590%2C2383%2C542%2C3114%2C961%2C2099%2C1662%2C2476%2C574%2C170%2C3217%2C26%2C2116%2C977%2C2250%2C566%2C526%2C1901%2C359%2C1229%2C2299%2C2820%2C604%2C1001%2C232%2C477%2C1338%2C3054%2C2623%2C225%2C1447%2C330%2C142%2C207%2C48%2C1857%2C360%2C3170%2C3160%2C2321%2C3135%2C1076%2C3082%2C766%2C449%2C1574%2C1579%2C2774%2C2763%2C1141%2C682%2C2971%2C353%2C375%2C984%2C2833%2C1155%2C1485%2C128%2C501%2C2944%2C1313%2C278%2C1617%2C490%2C2650%2C1843%2C155%2C387%2C2626%2C1913%2C1112%2C626%2C1294%2C461%2C2712%2C1562%2C1426%2C257%2C1358%2C951%2C782%2C85%2C2200%2C2281%2C1557%2C1486%2C425%2C3057%2C736%2C539%2C781%2C2847%2C3233%2C3015%2C1950%2C1698%2C520%2C2782%2C532%2C1193%2C55%2C1890%2C1681%2C57%2C2642%2C872%2C2354%2C1146%2C89%2C175%2C584%2C988%2C35%2C2453%2C1882%2C1421%2C665%2C3021%2C2758%2C1476%2C1207%2C2641%2C2670%2C3007%2C1584%2C904%2C930%2C1675%2C649%2C2972%2C2150%2C1318%2C648%2C642%2C2006%2C2245%2C3178%2C1764%2C2130%2C1028%2C1589%2C198%2C2550%2C1718%2C1098%2C1059%2C2683%2C3003%2C913%2C2019%2C2665%2C202%2C184%2C776%2C2183%2C1819%2C1459%2C2673%2C1984%2C1269%2C181%2C412%2C307%2C1671%2C2041%2C1463%2C830%2C154%2C2062%2C1101%2C326%2C1165%2C2543%2C681%2C335%2C1029%2C2715%2C2694%2C2105%2C2791%2C1957%2C554%2C2657%2C552%2C1867%2C1623%2C2505%2C74%2C890%2C440%2C1926%2C1289%2C299%2C2525%2C1282%2C1694%2C841%2C1898%2C1044%2C1350%2C91%2C2137%2C3183%2C1240%2C2815%2C3079%2C467%2C2121%2C474%2C481%2C867%2C1976%2C817%2C563%2C2751%2C3248%2C2953%2C229%2C673%2C68%2C2059%2C315%2C2514%2C1827%2C2501%2C2366%2C1947%2C222%2C2911%2C1504%2C25%2C2270%2C305%2C1253%2C928%2C1644%2C1526%2C3245%2C217%2C2648%2C1730%2C158%2C281%2C1851%2C1316%2C2630%2C2373%2C1418%2C36%2C2263%2C748%2C472%2C1655%2C317%2C711%2C132%2C1791%2C1254%2C1642%2C2180%2C2769%2C2071%2C546%2C537%2C1018%2C1125%2C2279%2C1007%2C1443%2C741%2C1833%2C1186%2C998%2C3119%2C2806%2C2240%2C3192%2C2076%2C529%2C1838%2C1773%2C1058%2C3166%2C2573%2C987%2C1150%2C3141%2C1535%2C2390%2C908%2C2580%2C284%2C1340%2C903%2C247%2C165%2C289%2C729%2C2%2C808%2C845%2C2125%2C1847%2C1231%2C2979%2C1249%2C147%2C2446%2C973%2C2961%2C2569%2C1046%2C1142%2C2095%2C1291%2C2601%2C2599%2C319%2C2960%2C2571%2C2857%2C1179%2C1052%2C1922%2C3048%2C1493%2C2948%2C2397%2C974%2C2629%2C1271%2C1668%2C1715%2C344%2C1613%2C2103%2C2949%2C636%2C1710%2C1406%2C1104%2C1133%2C2421%2C209%2C2837%2C3203%2C1118%2C1575%2C117%2C2428%2C2207%2C600%2C80%2C336%2C2472%2C457%2C1301%2C821%2C696%2C383%2C2532%2C1721%2C2179%2C2172%2C1431%2C92%2C3050%2C2253%2C2433%2C1805%2C3226%2C1727%2C1477%2C1164%2C2922%2C505%2C2739%2C1094%2C419%2C2178%2C995%2C1225%2C837%2C2909%2C2015%2C290%2C625%2C149%2C3208%2C712%2C210%2C406%2C2560%2C2312%2C19%2C3096%2C1030%2C365%2C2730%2C763%2C2593%2C3196%2C2021%2C1895%2C570%2C3123%2C1880%2C252%2C1159%2C883%2C2048%2C655%2C421%2C1998%2C2332%2C1367%2C271%2C1070%2C1024%2C3174%2C3117%2C2871%2C491%2C1863%2C2463%2C13%2C2493%2C105%2C1514%2C840%2C1647%2C597%2C2380%2C111%2C1411%2C408%2C1480%2C3265%2C2777%2C242%2C559%2C1588%2C32%2C443%2C2234%2C1795%2C580%2C2523%2C1257%2C846%2C31%2C1689%2C2307%2C2825%2C2706%2C1296%2C1553%2C2161%2C1303%2C2133%2C1654%2C968%2C675%2C15%2C3268%2C431%2C3016%2C382%2C2236%2C1506%2C139%2C129%2C3008%2C926%2C1246%2C859%2C1083%2C739%2C1293%2C876%2C3024%2C1792%2C662%2C168%2C135%2C1518%2C145%2C178%2C1131%2C2728%2C1876%2C124%2C772%2C1759%2C1974%2C2536%2C3026%2C1374%2C1528%2C2807%2C2303%2C653%2C1692%2C2677%2C2259%2C3064%2C509%2C2212%2C1015%2C367%2C976%2C716%2C1972%2C940%2C685%2C743%2C2265%2C21%2C523%2C1460%2C453%2C723%2C2500%2C1202%2C3162%2C351%2C1040%2C595%2C1755%2C1138%2C2926%2C1012%2C1498%2C835%2C2182%2C1267%2C1032%2C113%2C901%2C2191%2C152%2C2931%2C342%2C1419%2C862%2C341%2C2189%2C2540%2C3108%2C2284%2C64%2C2753%2C1473%2C881%2C2461%2C3186%2C45%2C405%2C507%2C1173%2C1963%2C309%2C1734%2C1733%2C3230%2C2113%2C2153%2C824%2C120%2C2568%2C2841%2C2386%2C2313%2C254%2C392%2C1321%2C2242%2C2442%2C2254%2C813%2C2014%2C2602%2C644%2C851%2C1820%2C399%2C2296%2C1811%2C436%2C2457%2C1802%2C94%2C213%2C2775%2C1450%2C3011%2C2863%2C2668%2C568%2C3250%2C3098%2C2273%2C2411%2C1129%2C791%2C1143%2C1355%2C2848%2C2231%2C3231%2C3095%2C1961%2C386%2C916%2C2043%2C1457%2C200%2C1352%2C525%2C2970%2C1621%2C27%2C2331%2C1902%2C161%2C1866%2C2001%2C3216%2C1310%2C109%2C2115%2C2651%2C1239%2C3035%2C2764%2C769%2C1556%2C1809%2C803%2C2744%2C2559%2C1766%2C60%2C1245%2C1400%2C691%2C1067%2C2615%2C1676%2C1388%2C3153%2C3134%2C346%2C3085%2C911%2C427%2C2072%2C82%2C2202%2C650%2C2624%2C895%2C1763%2C2965%2C69%2C1910%2C1157%2C1470%2C3076%2C224%2C3264%2C1982%2C1006%2C426%2C996%2C3222%2C3005%2C1435%2C1840%2C279%2C2069%2C956%2C483%2C498%2C629%2C1487%2C372%2C2951%2C3204%2C2028%2C3075%2C1330%2C1284%2C3041%2C1606%2C1160%2C99%2C869%2C1592%2C2022%2C790%2C533%2C2997%2C1697%2C1053%2C414%2C462%2C1770%2C2735%2C1209%2C263%2C991%2C2985%2C931%2C2246%2C615%2C476%2C1198%2C3210%2C1409%2C2219%2C2141%2C2464%2C1077%2C1716%2C293%2C1272%2C1781%2C1299%2C1663%2C967%2C2157%2C1611%2C322%2C469%2C3046%2C635%2C1088%2C575%2C1835%2C1566%2C709%2C40%2C310%2C192%2C699%2C1115%2C960%2C2363%2C1038%2C2908%2C2293%2C1707%2C543%2C3088%2C1777%2C2044%2C354%2C1437%2C2813%2C1064%2C2724%2C757%2C2577%2C9%2C2734%2C1217%2C3240%2C1600%2C603%2C2750%2C2527%2C90%2C1850%2C565%2C1964%2C3247%2C850%2C2818%2C2424%2C2696%2C1360%2C233%2C1013%2C1490%2C2198%2C1693%2C316%2C2947%2C1806%2C1738%2C2025%2C2954%2C11%2C2649%2C511%2C842%2C2367%2C899%2C3259%2C2000%2C2437%2C2531%2C2689%2C199%2C1979%2C1899%2C3066%2C2485%2C1737%2C1948%2C795%2C1609%2C794%2C944%2C1780%2C3223%2C3244%2C2122%2C674%2C2280%2C1317%2C280%2C957%2C273%2C471%2C2943%2C2596%2C2262%2C1936%2C1325%2C2512%2C131%2C1565%2C502%2C1286%2C314%2C1796%2C2998%2C1502%2C2638%2C1872%2C355%2C553%2C2058%2C1252%2C2643%2C555%2C1037%2C2513%2C37%2C855%2C195%2C1706%2C1788%2C679%2C680%2C831%2C1147%2C1960%2C2355%2C1241%2C2783%2C1441%2C647%2C1206%2C334%2C2292%2C1027%2C1680%2C423%2C2757%2C1319%2C1826%2C2454%2C2077%2C1222%2C2036%2C1747%2C174%2C820%2C1799%2C1571%2C422%2C905%2C1552%2C1194%2C41%2C3014%2C52%2C3084%2C1451%2C1453%2C866%2C2452%2C2223%2C593%2C770%2C188%2C402%2C3152%2C1097%2C641%2C838%2C2962%2C2664%2C616%2C640%2C1121%2C870%2C896%2C1468%2C3184%2C2068%2C1726%2C2903%2C2165%2C2347%2C1494%2C777%2C1906%2C2786%2C464%2C3235%2C1672%2C2325%2C1685%2C1891%2C6%2C2768%2C2327%2C1102%2C183%2C3189%2C2544%2C2541%2C439%2C362%2C1379%2C2607%2C1593%2C705%2C3053%2C2206%2C2496%2C2177%2C407%2C18%2C376%2C912%2C1432%2C1930%2C599%2C1393%2C1167%2C587%2C609%2C1235%2C298%2C95%2C243%2C2051%2C2682%2C148%2C753%2C2489%2C2655%2C726%2C2509%2C2171%2C2611%2C157%2C964%2C65%2C1909%2C935%2C203%2C2627%2C1213%2C81%2C1023%2C2742%2C2473%2C2084%2C1300%2C1199%2C86%2C624%2C2598%2C1158%2C2170%2C371%2C656%2C204%2C2335%2C1041%2C2921%2C1990%2C435%2C814%2C3195%2C2492%2C1482%2C2109%2C1412%2C884%2C1709%2C339%2C228%2C749%2C268%2C829%2C345%2C2090%2C1521%2C1862%2C2352%2C613%2C1082%2C121%2C1066%2C952%2C2691%2C494%2C487%2C1071%2C3058%2C1956%2C2778%2C2235%2C238%2C3081%2C253%2C448%2C2631%2C2278%2C2427%2C63%2C1637%2C179%2C1532%2C1105%2C713%2C2499%2C2805%2C2096%2C1784%2C938%2C1679%2C1830%2C1620%2C2241%2C1262%2C1290%2C1527%2C2162%2C1132%2C2370%2C2554%2C1925%2C2574%2C547%2C631%2C1616%2C1544%2C1538%2C396%2C258%2C1422%2C482%2C2620%2C949%2C499%2C1047%2C2138%2C1055%2C2447%2C3228%2C3140%2C141%2C909%2C3043%2C2981%2C2618%2C1124%2C1230%2C75%2C2793%2C2588%2C1163%2C450%2C1702%2C1405%2C1713%2C1060%2C2104%2C2126%2C2858%2C900%2C318%2C1729%2C2526%2C972%2C473%2C2572%2C1774%2C248%2C146%2C3202%2C1351%2C356%2C802%2C2720%2C2063%2C528%2C164%2C807%2C3269%2C2040%2C2632%2C882%2C1488%2C798%2C898%2C2725%2C1031%2C1273%2C2942%2C451%2C3139%2C2616%2C454%2C2538%2C1364%2C1408%2C2448%2C2969%2C634%2C2721%2C578%2C2551%2C695%2C978%2C2144%2C325%2C378%2C889%2C1233%2C540%2C1162%2C1615%2C3137%2C211%2C684%2C3065%2C1732%2C2073%2C861%2C337%2C2406%2C3172%2C76%2C2718%2C982%2C571%2C1214%2C1190%2C2592%2C389%2C1660%2C3207%2C1171%2C1345%2C2290%2C966%2C1123%2C2216%2C2314%2C992%2C236%2C758%2C1954%2C2843%2C218%2C706%2C14%2C3124%2C2587%2C1608%2C2973%2C2328%2C2999%2C3232%2C2474%2C234%2C594%2C2924%2C1903%2C2767%2C2188%2C1778%2C1859%2C160%2C2776%2C98%2C2901%2C1048%2C1278%2C2434%2C1000%2C1381%2C1061%2C2582%2C2054%2C1728%2C2785%2C3224%2C193%2C288%2C119%2C586%2C2859%2C410%2C3193%2C999%2C3019%2C1180%2C430%2C1185%2C2169%2C447%2C1741%2C2118%2C415%2C1130%2C189%2C2597%2C1292%2C1356%2C2330%2C2849%2C480%2C107%2C438%2C1153%2C1871%2C2385%2C87%2C1022%2C1832%2C2795%2C2704%2C953%2C221%2C3147%2C3176%2C1424%2C1560%2C417%2C784%2C1762%2C260%2C3080%2C2061%2C1844%2C1530%2C2504%2C762%2C1144%2C2798%2C1723%2C2621%2C144%2C1440%2C2524%2C381%2C1471%2C1814%2C906%2C1349%2C2205%2C2966%2C177%2C373%2C2213%2C773%2C1247%2C2940%2C22%2C205%2C3072%2C1309%2C1752%2C1576%2C1622%2C874%2C975%2C493%2C1708%2C1436%2C1591%2C1677%2C2174%2C2199%2C1320%2C1026%2C3002%2C2752%2C1390%2C1993%2C1469%2C1499%2C1646%2C3010%2C400%2C534%2C746%2C919%2C744%2C1268%2C633%2C1372%2C151%2C1977%2C1669%2C1825%2C1285%2C287%2C475%2C2595%2C932%2C1959%2C515%2C2545%2C1242%2C2761%2C2996%2C138%2C1107%2C1208%2C1874%2C1803%2C724%2C1201%2C519%2C17%2C2451%2C1274%2C2667%2C110%2C333%2C2210%2C2658%2C2780%2C646%2C446%2C2229%2C1220%2C1582%2C2306%2C1149%2C2900%2C2652%2C2337%2C2603%2C2243%2C2407%2C1087%2C1288%2C1238%2C33%2C1587%2C1559%2C7%2C1793%2C227%2C1701%2C1860%2C2443%2C264%2C255%2C806%2C2230%2C1885%2C182%2C1817%2C2707%2C556%2C2817%2C815%2C671%2C1511%2C2249%2C167%2C2423%2C692%2C1605%2C663%2C2431%2C854%2C1945%2C3120%2C969%2C1174%2C510%2C3020%2C393%2C2276%2C1501%2C3262%2C658%2C274%2C549%2C1508%2C3034%2C1128%2C1771%2C946%2C1520%2C2644%2C250%2C303%2C2148%2C1361%2C614%2C2963%2C1765%2C3155%2C130%2C53%2C1373%2C2925%2C1465%2C2239%2C1397%2C941%2C3029%2C583%2C2392%2C1879%2C1824%2C1869%2C3190%2C2342%2C591%2C832%2C2304%2C2804%2C2341%2C828%2C276%2C102%2C2465%2C1831%2C2992%2C2639%2C1218%2C1404%2C2398%2C1543%2C259%2C424%2C1625%2C163%2C1106%2C1402%2C1836%2C2986%2C2402%2C1531%2C2731%2C2929%2C1841%2C347%2C2738%2C2586%2C434%2C865%2C1184%2C3165%2C2770%2C3087%2C442%2C1577%2C2156%2C1572%2C689%2C1116%2C1329%2C1725%2C2379%2C727%2C3243%2C320%2C939%2C2619%2C811%2C1670%2C465%2C249%2C1612%2C819%2C1177%2C1189%2C1127%2C1537%2C894%2C1748%2C858%2C1298%2C2127%2C140%2C1900%2C385%2C954%2C1359%2C1479%2C2578%2C801%2C985%2C971%2C754%2C3151%2C479%2C847%2C1166%2C3061%2C3091%2C1563%2C2166%2C1003%2C1054%2C1800%2C2821%2C619%2C1717%2C2557%2C698%2C1634%2C621%2C524%2C1848%2C2176%2C2714%2C2495%2C598%2C3052%2C2486%2C780%2C2438%2C2317%2C3246%2C240%2C1433%2C1666%2C230%2C115%2C377%2C602%2C922%2C2319%2C2741%2C2628%2C1072%2C1787%2C1394%2C612%2C2772%2C936%2C1391%2C1277%2C1086%2C2794%2C701%2C214%2C564%2C3070%2C2708%2C2562%2C3094%2C2789%2C1650%2C2074%2C2539%2C2850%2C2547%2C731%2C2779%2C657%2C1865%2C2139%2C768%2C503%2C1756%2C2255%2C1636%2C2491%2C338%2C3105%2C761%2C1996%2C738%2C1775%2C1415%2C484%2C2334%2C1036%2C1078%2C1243%2C2530%2C1265%2C544%2C623%2C1512%2C3253%2C1196%2C1114%2C2389%2C2946%2C2564%2C2382%2C328%2C239%2C2635%2C122%2C269%2C628%2C878%2C1223%2C363%2C2277%2C2353%2C3198%2C3215%2C733%2C630%2C997%2C1449%2C608%2C3263%2C1234%2C1649%2C1314%2C2748%2C1798%2C1474%2C2535%2C522%2C125%2C1632%2C44%2C1423%2C2412%2C1687%2C667%2C1188%2C3142%2C2008%2C714%2C1280%2C1564%2C313%2C2017%2C2663%2C3023%2C2661%2C1324%2C397%2C3077%2C2934%2C1657%2C3009%2C2185%2C2717%2C1191%2C459%2C1495%2C771%2C1753%2C401%2C3187%2C2688%2C186%2C1797%2C1119%2C1914%2C3039%2C2756%2C1705%2C1919%2C1938%2C3000%2C915%2C3107%2C1586%2C1986%2C1456%2C404%2C516%2C2060%2C1551%2C702%2C2297%2C2214%2C2904%2C561%2C2195%2C2112%2C2555%2C2221%2C357%2C1307%2C3236%2C1812%2C1941%2C1769%2C455%2C1875%2C2132%2C297%2C963%2C3181%2C2612%2C2031%2C1889%2C2272%2C2692%2C2646%2C10%2C980%2C1596%2C550%2C2083%2C1081%2C1651%2C958%2C1569%2C1736%2C592%2C2542%2C1978%2C2364%2C1640%2C173%2C530%2C66%2C3067%2C2675%2C470%2C2026%2C1524%2C2360%2C793%2C1287%2C1696%2C3168%2C2403%2C654%2C2261%2C283%2C156%2C59%2C2091%2C2358%2C1226%2C2498%2C1256%2C1949%2C1744%2C2247%2C1853%2C219%2C1016%2C2480%2C2300%2C799%2C1170%2C925%2C1896%2C390%2C2368%2C1042%2C1515%2C1686%2C38%2C1955%2C196%2C945%2C1169%2C2784%2C206%2C118%2C959%2C1674%2C3194%2C1065%2C358%2C331%2C1659%2C2746%2C737%2C767%2C3037%2C2228%2C2070%2C1020%2C805%2C84%2C2173%2C437%2C194%2C2749%2C1768%2C220%2C1312%2C2395%2C2365%2C1021%2C1263%2C934%2C1989%2C948%2C2160%2C572%2C2450%2C1398%2C226%2C527%2C1145%2C1870%2C2549%2C1448%2C3229%2C2466%2C62%2C833%2C3146%2C2743%2C548%2C2020%2C2575%2C2204%2C2799%2C1772%2C418%2C2324%2C933%2C783%2C1357%2C348%2C2333%2C1152%2C789%2C49%2C2046%2C2967%2C993%2C627%2C1090%2C1308%2C2117%2C715%2C1934%2C2503%2C1916%2C2201%2C23%2C1722%2C388%2C3069%2C1425%2C950%2C2680%2C2957%2C1445%2C1845%2C1025%2C3083%2C1992%2C2478%2C1842%2C485%2C2340%2C778%2C2143%2C720%2C1270%2C2449%2C460%2C1645%2C324%2C1389%2C244%2C637%2C3220%2C2811%2C752%2C1232%2C3045%2C2941%2C379%2C1607%2C1386%2C1536%2C1639%2C1035%2C2617%2C452%2C579%2C295%2C1894%2C535%2C1618%2C3138%2C3136%2C77%2C683%2C541%2C2260%2C1215%2C2995%2C1712%2C2344%2C765%2C2552%2C897%2C312%2C1628%2C3219%2C2435%2C1002%2C237%2C2584%2C370%2C2722%2C2371%2C2923%2C2610%2C567%2C416%2C3212%2C3115%2C914%2C100%2C3206%2C965%2C300%2C1279%2C1439%2C2974%2C286%2C1395%2C2405%2C1075%2C2426%2C800%2C2232%2C1365%2C2432%2C1407%2C496%2C605%2C2987%2C1779%2C2581%2C1568%2C607%2C1807%2C1699%2C42%2C759%2C3093%2C1228%2C1073%2C235%2C2291%2C2591%2C1931%2C694%2C2844%2C816%2C1103%2C2244%2C1062%2C296%2C265%2C3169%2C171%2C2609%2C3261%2C445%2C2131%2C2687%2C1339%2C2338%2C3201%2C582%2C3257%2C1884%2C2120%2C557%2C718%2C1581%2C1604%2C2726%2C441%2C868%2C672%2C1140%2C983%2C275%2C197%2C2208%2C1731%2C853%2C751%2C1500%2C1746%2C1980%2C2136%2C2275%2C2685%2C3028%2C1295%2C2832%2C677%2C1111%2C907%2C3249%2C1868%2C3154%2C590%2C1210%2C664%2C1790%2C1878%2C2388%2C2938%2C2264%2C2964%2C1690%2C617%2C79%2C1420%2C352%2C2502%2C126%2C1034%2C251%2C369%2C1533%2C1548%2C651%2C176%2C3145%2C947%2C256%2C1823%2C2267%2C2810%2C920%2C428%2C2305%2C887%2C72%2C500%2C1496%2C1757%2C918%2C1682%2C1413%2C1108%2C1275%2C2107%2C2211%2C1014%2C2282%2C2760%2C843%2C1856%2C1491%2C1362%2C1804%2C2315%2C632%2C2357%2C394%2C2484%2C2257%2C610%2C514%2C2659%2C2444%2C725%2C513%2C50%2C2645%2C1519%2C1994%2C3252%2C2633%2C3173%2C797%2C2459%2C1136%2C1175%2C1236%2C1683%2C2413%2C645%2C1326%2C1382%2C1176%2C1452%2C2384%2C1039%2C1815%2C2637%2C1005%2C28%2C589%2C1337%2C215%2C687%2C3101%2C2098%2C150%2C2184%2C3161%2C3018%2C2298%2C2336%2C245%2C2511%2C2546%2C826%2C2494%2C1344%2C2666%2C332%2C2329%2C1099%2C1965%2C2980%2C745%2C34%2C2653%2C2656%2C2548%2C2082%2C3056%2C620%2C1410%2C2693%2C1434%2C2713%2C2625%2C1045%2C937%2C1619%2C3266%2C730%2C16%2C1069%2C2311%2C1224%2C368%2C3078%2C2556%2C994%2C611%2C1786%2C1849%2C492%2C2740%2C208%2C2788%2C2440%2C2140%2C1523%2C2271%2C3225%2C93%2C2773%2C292%2C2445%2C291%2C3071%2C3040%2C2429%2C374%2C2790%2C114%2C429%2C1306%2C1939%2C1328%2C73%2C409%2C1091%2C67%2C812%2C241%2C1958%2C3133%2C489%2C585%2C327%2C1392%2C1970%2C1080%2C1281%2C2819%2C732%2C1864%2C3214%2C1603%2C2233%2C622%2C1881%2C970%2C2771%2C24%2C1416%2C2759%2C2256%2C1658%2C2049%2C2057%2C1237%2C1635%2C2361%2C2175%2C1264%2C2490%2C747%2C159%2C2563%2C1633%2C47%2C1484%2C1017%2C270%2C1057%2C538%2C1602%2C521%2C2007%2C1332%2C162%2C1923%2C880%2C433%2C1399%2C1912%2C2164%2C986%2C786%2C740%2C1117%2C1008%2C3022%2C103%2C201%2C871%2C1401%2C719%2C1529%2C902%2C827%2C266%2C1353%2C1742%2C3128%2C2585%2C1624%2C1219%2C1695%2C2534%2C97%2C2983%2C1704%2C668%2C750%2C688%2C1749%2C774%2C1126%2C910%2C2128%2C693%2C1341%2C2684%2C1534%2C2570%2C2309%2C2737%2C804%2C83%2C2558%2C1385%2C2672%2C1818%2C962%2C755%2C1085%2C1714%2C1837%2C143%2C1403%2C2323%2C3049%2C1051%2C2268%2C3033%2C1497%2C497%2C518%2C2914%2C2906%2C3221%2C2852%2C2732%2C169%2C411%2C2155%2C2991%2C2399%2C1542%2C1711%2C2836%2C2579%2C478%2C3242%2C384%2C398%2C836%2C3182%2C3068%2C955%2C942%2C1735%2C1376%2C1888%2C3267%2C2030%2C2286%2C2369%2C2647%2C1595%2C190%2C2816%2C1750%2C1808%2C601%2C1739%2C231%2C1610%2C779%2C551%2C343%2C504%2C981%2C697%2C2823%2C3001%2C3177%2C857%2C707%2C1665%2C261%2C1782%2C2439%2C2252%2C2506%2C321%2C792%2C3209%2C3122%2C1079%2C1248%2C1590%2C2401%2C1652%2C1516%2C2462%2C924%2C2933%2C2301%2C760%2C863%2C2481%2C531%2C2027%2C172%2C1745%2C2594%2C2111%2C1366%2C223%2C721%2C1897%2C1043%2C1255%2C2660%2C669%2C282%2C420%2C1852%2C639%2C989%2C2372%2C1348%2C2945%2C2248%2C577%2C1137%2C2809%2C1227%2C216%2C852%2C643%2C2766%2C1120%2C2928%2C1475%2C1794%2C1187%2C2193%2C2636%2C2968%2C676%2C2092%2C1251%2C277%2C2456%2C3191%2C1192%2C879%2C3017%2C2640%2C2700%2C1095%2C1183%2C1444%2C2747%2C1883%2C1846%2C2671%2C133%2C123%2C304%2C2600%2C2515%2C2417%2C1631%2C1828%2C2605%2C2294%2C56%2C3006%2C1151%2C306%2C1204%2C70%2C839%2C166%2C88%2C1578%2C2225%2C1009%2C30%2C403%2C466%2C134%2C3038%2C618%2C2151%2C848%2C1829%2C1904%2C1629%2C1761%2C2755%2C1323%2C3237%2C1455%2C3150%2C2662%2C3164%2C2729%2C703%2C1134%2C1100%2C1377%2C2488%2C1461%2C185%2C2487%2C3188%2C1719%2C2669%2C1691&limit=20&page=28

I got:
```
Request-URI Too Large
The requested URL's length exceeds the capacity limit for this server.
Apache/2.2.12 (Ubuntu) Server at 188.40.132.3 Port 80
```

**Comment by davorg** [comment] 2018-12-06 17:07
Wow. That's *horrible*, isn't it!?! I guess it's just more evidence that this version of MT really wasn't intended for our use case.

I think that all we can do is to gently keep encouraging the authors of the replacement system to work as quickly as possible :-)

**Comment by ap** [comment] 2022-12-29 18:41
This is a duplicate of #204.

**Closed by ap** 2022-12-29 18:41 UTC
Labels: bug
