### ISSUE TITLE
Add SSL to the site.

### ISSUE THREAD

**Issue by matthewpersico** [blogs-perl-org/blogs.perl.org#410] opened 2021-11-16 14:37 UTC
Is it really as easy as http://blogs.perl.org/users/nerdvana/2021/11/ssl-is-easy-with-traefik.html makes it out to be?

**Comment by ap** [comment] 2021-11-16 15:50
Dupe of #254

**Closed as completed by ap** 2021-11-16 15:50 UTC

**Comment by ap** [comment] 2021-11-17 20:11
(The answer being yes, and the longer answer being in the other ticket. Sorry I was curt yesterday, I was in a hurry.)

**Comment by matthewpersico** [comment] 2021-11-18 01:37
No worries.
