### ISSUE TITLE
/var/www/users/erlangenpm/index.html in entry list

### ISSUE THREAD

**Issue by bedivere** [blogs-perl-org/blogs.perl.org#86] opened 2010-07-09 09:19 UTC
The first blog entry of http://blogs.perl.org/users/erlangenpm/ has "/var/www/users/erlangenpm/index.html" added to its summary, which never occurs in the blog entry itself.

**Comment by ap** [comment] 2012-04-15 08:51
This issue is a duplicate of #80.

**Closed as completed by ap** 2012-04-15 08:51 UTC
Labels: bug
