### ISSUE TITLE
Summary cut off

### ISSUE THREAD

**Issue by acme** [blogs-perl-org/blogs.perl.org#90] opened 2010-07-31 07:57 UTC
At the moment, http://blogs.perl.org/users/acme/ shows odd HTML as the summary of my latest post:

By a happy coincidence, the regular London Perl Mongers social meeting falls on the second day of the YAPC::Europe Perl conference in Pisa, Italy. We shall be holding it at the /var/www/users/acme/index.html

**Comment by ap** [comment] 2012-04-15 08:33
This is a duplicate of #80.

**Closed as completed by ap** 2012-04-15 08:33 UTC
Labels: bug
